# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='belt_app.User'),
            preserve_default=False,
        ),
    ]
